# Dependencies

collections:
  - education
  - training
  - work_experience
  - teaching_experience
  - news
  - projects
  
# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Tiziana Mancinelli
tagline:          '#digitalhuminities #textualscholarship'
description:      '#digitalhuminities #textualscholarship'
url:              http://tmancinelli.github.io
baseurl:          /

author:
  name:           'Tiziana Mancinelli'
  url:            https://twitter.com/tizmancinelli

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tmancinelli/myWebsite
